server:
  port: 8080
  servlet:
    context-path: /
application:
  remote:
    base-url: https://api.github.com
    refresh-rate: 5  # Rate, in minutes, at which to refresh the cached urls
    eviction-time: 10 # Time, in minutes, after which to consider proxied requests in cache invalid
    cached-endpoints: # FIXME Make org configurable
      org: /orgs/parse-community
      members: /orgs/parse-community/members
      repos: /orgs/parse-community/repos
    authorization:
      header: Authorization
      value: token {GITHUB-API-TOKEN}
    pagination-header: link


    # FIXME Reimplement once finished easier idea
    #    navigation-extension: /
    #    cached-relations:
    #      -
    #        relation: organization_url
    #        children:
    #          - relation: repos_url
    #          - relation: members_url
    #    variables:
    #      org: parse-community