server:
  port: 8080
  servlet:
    context-path: /
application:
  cache:
    eviction-time: 5
    redis:
      host: localhost
  remote:
    base-url: https://api.github.com
    organization: lightbend
    pagination-header: link
    authorization:
      header: Authorization
      value: token {GITHUB-API-TOKEN}